# Generated by Django 5.1.6 on 2025-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='campo1',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='campo2',
        ),
        migrations.AddField(
            model_name='contrato',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fin_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contrato',
            name='inicio_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proveedor',
            field=models.CharField(default='Proveedor Desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
